<a href="https://colab.research.google.com/github/Hygl0110/SelfDataLearnig/blob/normalize_vinilosDB/normalizacion_datos_vinilos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np



#tabla en formato ancho raw como se estaba trabajando hasta la fecha
df = pd.read_excel('datosRAW_01.xlsx')
df

,ID_produccion,Fecha,Maquina,Operario,Referencia,Pacas_producidas,Horas_trabajadas,Turno,Codigo_1_en_horas,Sub_Codigo_de_paro_1,...,Codigo_10_en_horas,Codigo_11_en_horas,Codigo_12_en_horas,Codigo_13_en_horas,Codigo_14_en_horas,Codigo_15_en_horas,Codigo_16_en_horas,Codigo_17_en_horas,Codigo_18_en_horas,Observaciones
0,20250904-42,2025-09-04,Vinilos_4,Ana,Parchesitos 22cc (6 col),42.0,,2pm-10pm (Turno 2),0.75,1.2.C Cambio de Valvula,...,0.0,0.0,0.0,0.0,0.0,0.0,0.666667,0.05,0.0,NaN
1,20250904-42,2025-09-04,Vinilos_4,Ana,Parchesitos 22cc (6 col),NaN,NaN,2pm-10pm (Turno 2),0.00,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00,0.0,NaN
2,20250904-42,2025-09-04,Vinilos_4,Ana,Parchesitos 22cc (6 col),NaN,NaN,2pm-10pm (Turno 2),0.00,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00,0.0,NaN
3,20250911-43,2025-09-11,Vinilos_4,Natalia P.,Parchesitos 22cc (6 col),54.0,9,10pm-6am (Turno 3),0.00,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.666667,0.05,0.0,NaN
4,20250911-43,2025-09-11,Vinilos_4,Natalia P.,Parchesitos 22cc (6 col),NaN,NaN,10pm-6am (Turno 3),0.00,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4729,20240102-31,2024-01-02,Vinilos_3,Alexandra,Torre 22cc (6 col),NaN,NaN,6am-2pm (Turno 1),0.00,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00,0.0,NaN
4730,20240101-2,2024-01-01,Vinilos_2,No aplica,NaN,0.0,0,NaN,0.00,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00,0.0,NaN
4731,20240101-4,2024-01-01,Vinilos_4,No aplica,NaN,0.0,0,NaN,0.00,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00,0.0,NaN
4732,20240101-3,2024-01-01,Vinilos_3,No aplica,NaN,0.0,0,NaN,0.00,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00,0.0,NaN
4733,20240101-1,2024-01-01,Vinilos_1,No aplica,NaN,0.0,0,NaN,0.00,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00,0.0,NaN

In [ ]:
#nombres de las columnas de la base de datos, para copiar y pegar en los arrays
df.columns.to_list()

['ID_produccion',
 'Fecha',
 'Maquina',
 'Operario',
 'Referencia',
 'Pacas_producidas',
 'Horas_trabajadas',
 'Turno',
 'Codigo_1_en_horas',
 'Sub_Codigo_de_paro_1',
 'Codigo_2_en_horas',
 'Codigo_3_en_horas',
 'Subcodigo_3',
 'Codigo_4_en_horas',
 'Codigo_5_en_horas',
 'Subcodigo_5',
 'Área_involucrada_en_subcodigo_5',
 'Personal_involucrado',
 'Codigo_6_en_horas',
 'Codigo_7_en_horas',
 'Codigo_8_en_horas',
 'Codigo_9_en_horas',
 'Codigo_10_en_horas',
 'Codigo_11_en_horas',
 'Codigo_12_en_horas',
 'Codigo_13_en_horas',
 'Codigo_14_en_horas',
 'Codigo_15_en_horas',
 'Codigo_16_en_horas',
 'Codigo_17_en_horas',
 'Codigo_18_en_horas',
 'Observaciones']

In [ ]:
#tabla de porduccion
#nombres de las columnas de produccion
cols_info = ['ID_produccion', 'Fecha', 'Maquina', 'Operario', 'Referencia', 'Turno']

df_produccion = df.groupby(cols_info, as_index=False)[['Pacas_producidas', 'Horas_trabajadas']].sum()
df_produccion.head()

,ID_produccion,Fecha,Maquina,Operario,Referencia,Turno,Pacas_producidas,Horas_trabajadas
0,20240102-11,2024-01-02,Vinilos_1,Lorena T.,Pintorcitos 15cc (6 col),6am-2pm (Turno 1),43.0,8
1,20240102-12,2024-01-02,Vinilos_1,Erika H.,Pintorcitos 15cc (6 col),2pm-10pm (Turno 2),40.0,8
2,20240102-13,2024-01-02,Vinilos_1,Monica,Pintorcitos 15cc (6 col),10pm-6am (Turno 3),41.0,8
3,20240102-2p,2024-01-02,Vinilos_2,Helen,Parchesitos 125 cc,6am-4:30pm,374.0,10.5
4,20240102-31,2024-01-02,Vinilos_3,Alexandra,Torre 22cc (6 col),6am-2pm (Turno 1),67.0,8

In [ ]:
#extraccion unicamente de los nombres de las columnas que contengan codigo y en horas
cols_paros = [c for c in df.columns if c.startswith("Codigo_") and c.endswith("_en_horas")]
cols_paros

['Codigo_1_en_horas',
 'Codigo_2_en_horas',
 'Codigo_3_en_horas',
 'Codigo_4_en_horas',
 'Codigo_5_en_horas',
 'Codigo_6_en_horas',
 'Codigo_7_en_horas',
 'Codigo_8_en_horas',
 'Codigo_9_en_horas',
 'Codigo_10_en_horas',
 'Codigo_11_en_horas',
 'Codigo_12_en_horas',
 'Codigo_13_en_horas',
 'Codigo_14_en_horas',
 'Codigo_15_en_horas',
 'Codigo_16_en_horas',
 'Codigo_17_en_horas',
 'Codigo_18_en_horas']

In [ ]:
#uso de melt para convertir las columnas en filas para generar una tabla, cada una es un posible paro
df_paros = df.melt(
    id_vars=['ID_produccion'],
    value_vars=cols_paros,
    var_name='Codigo_columna',
    value_name='Tiempo_en_horas'
)
df_paros.head()

  ID_produccion     Codigo_columna  Tiempo_en_horas
0   20250904-42  Codigo_1_en_horas             0.75
1   20250904-42  Codigo_1_en_horas             0.00
2   20250904-42  Codigo_1_en_horas             0.00
3   20250911-43  Codigo_1_en_horas             0.00
4   20250911-43  Codigo_1_en_horas             0.00

In [ ]:
#crear una nueva columnas y extrar sunicamente el numero del codigo de paro
df_paros['Codigo_de_paro'] = df_paros['Codigo_columna'].str.extract(r'(\d+)').astype(int)
df_paros.head()

  ID_produccion     Codigo_columna  Tiempo_en_horas  Codigo_de_paro
0   20250904-42  Codigo_1_en_horas             0.75               1
1   20250904-42  Codigo_1_en_horas             0.00               1
2   20250904-42  Codigo_1_en_horas             0.00               1
3   20250911-43  Codigo_1_en_horas             0.00               1
4   20250911-43  Codigo_1_en_horas             0.00               1

In [ ]:
df_paros = df_paros[df_paros['Tiempo_en_horas'] > 0]
df_paros

      ID_produccion      Codigo_columna  Tiempo_en_horas  Codigo_de_paro
0       20250904-42   Codigo_1_en_horas         0.750000               1
45      20250903-32   Codigo_1_en_horas         3.083333               1
76      20250910-21   Codigo_1_en_horas         0.416667               1
77      20250910-21   Codigo_1_en_horas         0.416667               1
88      20250901-21   Codigo_1_en_horas         0.416667               1
...             ...                 ...              ...             ...
82004   20250114-11  Codigo_18_en_horas         0.333333              18
82017   20250113-11  Codigo_18_en_horas         0.533333              18
82076   20250103-21  Codigo_18_en_horas         1.000000              18
82148   20241223-42  Codigo_18_en_horas         0.500000              18
82181   20241219-43  Codigo_18_en_horas         1.000000              18

[12589 rows x 4 columns]

In [ ]:
#insertar los subcodigos a la tabla de paros iniciando todos con NA
df_paros['Subcodigo'] = "NA"
df_paros.head()

   ID_produccion     Codigo_columna  Tiempo_en_horas  Codigo_de_paro Subcodigo
0    20250904-42  Codigo_1_en_horas         0.750000               1        NA
45   20250903-32  Codigo_1_en_horas         3.083333               1        NA
76   20250910-21  Codigo_1_en_horas         0.416667               1        NA
77   20250910-21  Codigo_1_en_horas         0.416667               1        NA
88   20250901-21  Codigo_1_en_horas         0.416667               1        NA

In [ ]:
#relacionar el valor de subcodigo de la tabla df, con cada codigo para cada codigo 1, 3 y 5
df_paros.loc[df_paros['Codigo_de_paro'] == 1, 'Subcodigo'] = df['Sub_Codigo_de_paro_1']
df_paros.loc[df_paros['Codigo_de_paro'] == 3, 'Subcodigo'] = df['Subcodigo_3']
df_paros.loc[df_paros['Codigo_de_paro'] == 5, 'Subcodigo'] = df['Subcodigo_5']
df_paros

,ID_produccion,Codigo_columna,Tiempo_en_horas,Codigo_de_paro,Subcodigo
0,20250904-42,Codigo_1_en_horas,0.750000,1,1.2.C Cambio de Valvula
45,20250903-32,Codigo_1_en_horas,3.083333,1,1.5 SISTEMA DE ALIMENTACIÓN DE TAPA
76,20250910-21,Codigo_1_en_horas,0.416667,1,1.2.C Cambio de Valvula
77,20250910-21,Codigo_1_en_horas,0.416667,1,1.2.C Cambio de Valvula
88,20250901-21,Codigo_1_en_horas,0.416667,1,1.2.C Cambio de Valvula
...,...,...,...,...,...
82004,20250114-11,Codigo_18_en_horas,0.333333,18,NA
82017,20250113-11,Codigo_18_en_horas,0.533333,18,NA
82076,20250103-21,Codigo_18_en_horas,1.000000,18,NA
82148,20241223-42,Codigo_18_en_horas,0.500000,18,NA
82181,20241219-43,Codigo_18_en_horas,1.000000,18,NA

In [ ]:
#conservar unicamente las columnas de interes y organizar
df_paros = df_paros[['ID_produccion', 'Codigo_de_paro', 'Subcodigo', 'Tiempo_en_horas']]
df_paros

,ID_produccion,Codigo_de_paro,Subcodigo,Tiempo_en_horas
0,20250904-42,1,1.2.C Cambio de Valvula,0.750000
45,20250903-32,1,1.5 SISTEMA DE ALIMENTACIÓN DE TAPA,3.083333
76,20250910-21,1,1.2.C Cambio de Valvula,0.416667
77,20250910-21,1,1.2.C Cambio de Valvula,0.416667
88,20250901-21,1,1.2.C Cambio de Valvula,0.416667
...,...,...,...,...
82004,20250114-11,18,NA,0.333333
82017,20250113-11,18,NA,0.533333
82076,20250103-21,18,NA,1.000000
82148,20241223-42,18,NA,0.500000
82181,20241219-43,18,NA,1.000000

In [ ]:
df_produccion.to_excel("produccion_procesada.xlsx", index=False)
df_paros.to_excel("paros_procesados.xlsx", index=False)